# Import Pydantic BaseModel for data validation
from pydantic import BaseModel, Field
# Import Pydantic ConfigDict for model configuration
from pydantic import ConfigDict
# Import Optional and datetime for optional fields and timestamps
from typing import Optional
from datetime import datetime
# Import PyObjectId for MongoDB ObjectId validation
from bson import ObjectId

# Custom validator for MongoDB ObjectId to work with Pydantic v2
class PyObjectId(str):
    """
    Custom class to handle MongoDB ObjectId in Pydantic models.
    """
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type, handler):
        # Import necessary Pydantic core schema components
        from pydantic_core import core_schema
        # Return core schema with string input and validation
        return core_schema.no_info_plain_validator_function(cls.validate)

    @classmethod
    def validate(cls, v):
        # Check if value is already an ObjectId instance
        if isinstance(v, ObjectId):
            # Return string representation if already an ObjectId
            return str(v)
        # Check if value is a valid ObjectId string
        if isinstance(v, str) and ObjectId.is_valid(v):
            # Return string if valid ObjectId format
            return v
        # Raise error if invalid ObjectId format
        raise ValueError("Invalid ObjectId")

# Pydantic model for patient input request
class PatientInput(BaseModel):
    """
    Schema for patient input data with validation rules.
    """
    # Configure Pydantic v2 model settings
    model_config = ConfigDict(
        # Allow population by field name
        populate_by_name=True,
        # Use enum values in JSON serialization
        use_enum_values=True
    )
    
    # Required field for patient name, must be non-empty string
    name: str = Field(..., min_length=1, description="Patient's full name")
    # Required field for medical problem description, must be non-empty string
    problem: str = Field(..., min_length=1, description="Primary medical problem or symptom")
    # Optional field for additional information about the problem
    message: Optional[str] = Field(None, description="Additional details or context about the problem")

# Pydantic model for AI response
class AIResponse(BaseModel):
    """
    Schema for AI-generated medical response.
    """
    # Required field containing the AI's diagnosis and recommendations
    response: str = Field(..., description="AI-generated medical diagnosis and recommendations")

# Pydantic model for complete chat session stored in database
class ChatSession(BaseModel):
    """
    Schema for chat session data stored in MongoDB.
    """
    # Configure Pydantic v2 model settings
    model_config = ConfigDict(
        # Allow population by field name (for _id alias)
        populate_by_name=True,
        # Use enum values in JSON serialization
        use_enum_values=True,
        # Use ObjectId for JSON encoding
        json_encoders={ObjectId: str}
    )
    
    # Optional MongoDB ObjectId for document identification (auto-generated by MongoDB)
    id: Optional[PyObjectId] = Field(default=None, alias="_id")
    # Required patient name from input
    patient_name: str = Field(..., description="Name of the patient")
    # Required primary problem description
    problem: str = Field(..., description="Primary medical problem or symptom")
    # Optional additional information provided by patient
    additional_info: Optional[str] = Field(None, description="Additional context or details")
    # Required AI-generated response with diagnosis and recommendations
    ai_response: str = Field(..., description="AI's medical diagnosis and recommendations")
    # Required timestamp of when the session was created
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Session creation timestamp")
    # Optional pinned status to keep important chats at the top
    pinned: Optional[bool] = Field(default=False, description="Whether this chat is pinned")

# Pydantic model for API response containing chat session data
class ChatSessionResponse(BaseModel):
    """
    Schema for API response when returning chat session data.
    """
    # Configure Pydantic v2 model settings
    model_config = ConfigDict(
        # Use enum values in JSON serialization
        use_enum_values=True,
        # Use datetime as string in JSON
        json_encoders={datetime: str}
    )
    
    # Required patient name
    patient_name: str = Field(..., description="Name of the patient")
    # Required primary problem
    problem: str = Field(..., description="Primary medical problem or symptom")
    # Optional additional information
    additional_info: Optional[str] = Field(None, description="Additional context or details")
    # Required AI response
    ai_response: str = Field(..., description="AI's medical diagnosis and recommendations")
    # Required timestamp
    timestamp: datetime = Field(..., description="Session creation timestamp")
    # Required MongoDB document ID as string
    id: str = Field(..., description="Unique session identifier")
    # Optional pinned status
    pinned: Optional[bool] = Field(default=False, description="Whether this chat is pinned")

# Pydantic model for chat session update request
class ChatSessionUpdate(BaseModel):
    """
    Schema for updating a chat session (rename, pin, etc.).
    """
    # Configure Pydantic v2 model settings
    model_config = ConfigDict(
        # Allow population by field name
        populate_by_name=True,
        # Use enum values in JSON serialization
        use_enum_values=True
    )
    
    # Optional problem/name field for renaming
    problem: Optional[str] = Field(None, description="New problem/name for the chat")
    # Optional pinned status
    pinned: Optional[bool] = Field(None, description="Pin status for the chat")
